### ISSUE TITLE
登陆时崩溃

### ISSUE THREAD

**Issue by YosakuraTohu** [novel-rs/cli#87]
```shell
[kinare@kinare Novel]$ novel-cli download --source sfacg --format mdbook [novel_id]
Username: [user_name]
thread 'main' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', /home/kinare/.cargo/registry/src/github.com-1ecc6299db9ec823/zbus-3.12.0/src/utils.rs:47:14
已放弃 (核心已转储)
```
没有在其它用户环境测试
版本信息：
```shell
[kinare@kinare Novel]$ novel-cli --version
novel-cli 0.2.1
Executable path: /home/kinare/.cargo/bin/novel-cli
Config directory: /home/kinare/.config/some-source
Data directory: /home/kinare/.local/share/some-source
```

**Comment by TerakomariGandesblood** [comment]
已确认，仅在Linux上存在该问题，将在今天晚些时候修完。但由于[108978](https://github.com/rust-lang/rust/issues/108978)，在Windows上编译失败，我将在下个月Rust 1.70发布之后release新版本。

**Comment by YosakuraTohu** [comment]
我试着复现了一下，发现是novel-api里keyring的问题，应该是Features没有写对。
- cargo.toml
```toml
[package]
name = "test-for-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyring = { version = "2.0.3", default-features = false, features = [
  "linux-secret-service-rt-tokio-crypto-rust",
] }
tokio = { version = "1.28.1", default-features = false, features = [
  "macros",
  "fs",
  "rt-multi-thread",
  "parking_lot",
] }
```
- main.rs
```rust
async fn test_function() -> Result<String, keyring::Error> {
    let password = "test-username";
    let keyring = Keyring::new("hello", password)?;

    keyring.get_password()
}

#[tokio::main]
async fn main() {
    println!("{:#?}", test_function().await);
}
```
- shell

```shell
[kinare@kinare test-for-api]$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/test-for-api`
thread 'main' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', /home/kinare/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zbus-3.13.1/src/utils.rs:47:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
